// packages/react/src/primitives/List.tsx
import type { FontItem } from "@font-family-input/core";
import { useVirtualizer } from "@tanstack/react-virtual";
import { type HTMLAttributes, type ReactNode, forwardRef, useEffect, useRef } from "react";
import { ItemProvider, useFontInputContext } from "../context";
import { mergeRefs } from "../internal";

export interface FontInputListProps extends Omit<HTMLAttributes<HTMLDivElement>, "children"> {
  /** Render a single option. Wrapped + positioned by the virtualizer. */
  children: (font: FontItem, index: number) => ReactNode;
  /** Estimated row height in px (drives virtualization). Default 36. */
  estimateSize?: number;
  /** Extra rows to render beyond the viewport. Default 8. */
  overscan?: number;
}

/**
 * Virtualized listbox. Owns the scroll container and renders only the visible
 * options via `@tanstack/react-virtual`. Set a `max-height` via CSS to bound it.
 */
export const List = forwardRef<HTMLDivElement, FontInputListProps>(function List(
  { children, estimateSize = 36, overscan = 8, style, ...rest },
  ref,
) {
  const { state, ids } = useFontInputContext("List");
  const scrollRef = useRef<HTMLDivElement | null>(null);

  const virtualizer = useVirtualizer({
    count: state.filtered.length,
    getScrollElement: () => scrollRef.current,
    estimateSize: () => estimateSize,
    overscan,
  });

  // Keep the highlighted option in view during keyboard navigation.
  useEffect(() => {
    if (state.highlightedIndex >= 0) {
      virtualizer.scrollToIndex(state.highlightedIndex);
    }
  }, [state.highlightedIndex, virtualizer]);

  const items = virtualizer.getVirtualItems();

  return (
    <div
      ref={mergeRefs(ref, scrollRef)}
      id={ids.listbox}
      role="listbox"
      style={{ overflow: "auto", ...style }}
      {...rest}
    >
      <div style={{ height: virtualizer.getTotalSize(), position: "relative", width: "100%" }}>
        {items.map((virtualItem) => {
          const font = state.filtered[virtualItem.index];
          if (!font) return null;
          return (
            <div
              key={virtualItem.key}
              data-index={virtualItem.index}
              ref={virtualizer.measureElement}
              style={{
                position: "absolute",
                top: 0,
                left: 0,
                width: "100%",
                transform: `translateY(${virtualItem.start}px)`,
              }}
            >
              <ItemProvider value={{ font, index: virtualItem.index }}>
                {children(font, virtualItem.index)}
              </ItemProvider>
            </div>
          );
        })}
      </div>
    </div>
  );
});

// packages/svelte/src/lib/List.svelte
<script lang="ts">
import type { FontItem } from "@font-family-input/core";
import { type Snippet, getContext } from "svelte";
import { FONT_INPUT_KEY, type FontInputContext } from "./context";

interface Props {
  estimateSize?: number;
  overscan?: number;
  children: Snippet<[FontItem, number]>;
  [key: string]: unknown;
}

let { estimateSize = 36, overscan = 8, children, ...rest }: Props = $props();
const { state: fontState, ids } = getContext<FontInputContext>(FONT_INPUT_KEY);

// Fixed-height windowing — the per-framework virtualization strategy for the
// Svelte adapter (deterministic and dependency-free, like the Web Component).
let scrollEl = $state<HTMLDivElement>();
let scrollTop = $state(0);
let viewport = $state(300);

$effect(() => {
  if (scrollEl) viewport = scrollEl.clientHeight || 300;
});

const count = $derived($fontState.filtered.length);
const start = $derived(Math.max(0, Math.floor(scrollTop / estimateSize) - overscan));
const end = $derived(Math.min(count, Math.ceil((scrollTop + viewport) / estimateSize) + overscan));
const rows = $derived(
  $fontState.filtered.slice(start, end).map((font, i) => ({ font, index: start + i })),
);

// Keep the highlighted option in view.
$effect(() => {
  const hi = $fontState.highlightedIndex;
  if (hi >= 0 && scrollEl) {
    const top = hi * estimateSize;
    const bottom = top + estimateSize;
    if (top < scrollEl.scrollTop) scrollEl.scrollTop = top;
    else if (bottom > scrollEl.scrollTop + scrollEl.clientHeight)
      scrollEl.scrollTop = bottom - scrollEl.clientHeight;
  }
});
</script>

<div
  bind:this={scrollEl}
  id={ids.listbox}
  role="listbox"
  style="overflow:auto"
  onscroll={(e) => {
    scrollTop = e.currentTarget.scrollTop;
  }}
  {...rest}
>
  <div style="height:{count * estimateSize}px;position:relative;width:100%">
    {#each rows as row (row.font.family)}
      <div
        data-index={row.index}
        style="position:absolute;top:0;left:0;width:100%;height:{estimateSize}px;transform:translateY({row.index *
          estimateSize}px)"
      >
        {@render children(row.font, row.index)}
      </div>
    {/each}
  </div>
</div>
