// packages/react/src/primitives/Search.tsx
import { handleComboboxKey } from "@font-family-input/core";
import { type InputHTMLAttributes, forwardRef } from "react";
import { useFontInputContext } from "../context";
import { comboboxTarget, mergeRefs } from "../internal";

export type FontInputSearchProps = Omit<
  InputHTMLAttributes<HTMLInputElement>,
  "value" | "onChange"
>;

/** The filter textbox. Drives the combobox keyboard interaction. */
export const Search = forwardRef<HTMLInputElement, FontInputSearchProps>(function Search(
  { onKeyDown, placeholder = "Search fonts…", ...rest },
  ref,
) {
  const { store, state, ids, inputRef } = useFontInputContext("Search");
  const activeId = state.highlightedIndex >= 0 ? ids.option(state.highlightedIndex) : undefined;

  return (
    <input
      ref={mergeRefs(ref, inputRef)}
      id={ids.input}
      type="text"
      role="combobox"
      autoComplete="off"
      aria-autocomplete="list"
      aria-expanded={state.open}
      aria-controls={ids.listbox}
      aria-activedescendant={activeId}
      placeholder={placeholder}
      value={state.search}
      onChange={(event) => store.setSearch(event.target.value)}
      onKeyDown={(event) => {
        onKeyDown?.(event);
        if (event.defaultPrevented) return;
        if (handleComboboxKey(comboboxTarget(store), event)) event.preventDefault();
      }}
      {...rest}
    />
  );
});

// packages/svelte/src/lib/Search.svelte
<script lang="ts">
import { handleComboboxKey } from "@font-family-input/core";
import { getContext } from "svelte";
import { FONT_INPUT_KEY, type FontInputContext } from "./context";
import { comboboxTarget } from "./internal";

interface Props {
  placeholder?: string;
  [key: string]: unknown;
}

let { placeholder = "Search fonts…", ...rest }: Props = $props();
const { store, state: fontState, ids, refs } = getContext<FontInputContext>(FONT_INPUT_KEY);
</script>

<input
  bind:this={refs.input}
  id={ids.input}
  type="text"
  role="combobox"
  autocomplete="off"
  aria-autocomplete="list"
  aria-expanded={$fontState.open}
  aria-controls={ids.listbox}
  aria-activedescendant={$fontState.highlightedIndex >= 0
    ? ids.option($fontState.highlightedIndex)
    : undefined}
  {placeholder}
  value={$fontState.search}
  oninput={(e) => store.setSearch(e.currentTarget.value)}
  onkeydown={(e) => {
    if (handleComboboxKey(comboboxTarget(store), e)) e.preventDefault();
  }}
  {...rest}
/>
