// packages/react/src/primitives/Trigger.tsx
import { handleComboboxKey } from "@font-family-input/core";
import { type ButtonHTMLAttributes, type ReactNode, forwardRef } from "react";
import { useFontInputContext } from "../context";
import { comboboxTarget, mergeRefs } from "../internal";

export interface FontInputTriggerProps
  extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, "children"> {
  /** Text shown when no font is selected. */
  placeholder?: string;
  /** Custom content. Receives the current value; defaults to value-or-placeholder. */
  children?: ReactNode | ((value: string) => ReactNode);
  /** Apply the selected font as the button's `font-family` for preview. Default true. */
  previewFont?: boolean;
}

/** The button that opens the picker and shows the current selection. */
export const Trigger = forwardRef<HTMLButtonElement, FontInputTriggerProps>(function Trigger(
  {
    placeholder = "Select font…",
    children,
    previewFont = true,
    onClick,
    onKeyDown,
    style,
    ...rest
  },
  ref,
) {
  const { store, state, ids, triggerRef } = useFontInputContext("Trigger");

  const content =
    typeof children === "function"
      ? children(state.value)
      : (children ?? (state.value || placeholder));

  return (
    <button
      type="button"
      ref={mergeRefs(ref, triggerRef)}
      id={ids.trigger}
      aria-haspopup="listbox"
      aria-expanded={state.open}
      aria-controls={state.open ? ids.listbox : undefined}
      data-state={state.open ? "open" : "closed"}
      data-placeholder={state.value ? undefined : ""}
      style={previewFont && state.value ? { fontFamily: state.value, ...style } : style}
      onClick={(event) => {
        onClick?.(event);
        if (!event.defaultPrevented) store.toggle();
      }}
      onKeyDown={(event) => {
        onKeyDown?.(event);
        if (event.defaultPrevented) return;
        if (handleComboboxKey(comboboxTarget(store), event)) event.preventDefault();
      }}
      {...rest}
    >
      {content}
    </button>
  );
});

// packages/svelte/src/lib/Trigger.svelte
<script lang="ts">
  import { getContext, type Snippet } from "svelte";
  import { handleComboboxKey } from "@font-family-input/core";
  import { type FontInputContext, FONT_INPUT_KEY } from "./context";
  import { comboboxTarget } from "./internal";

  interface Props {
    placeholder?: string;
    previewFont?: boolean;
    children?: Snippet<[string]>;
    [key: string]: unknown;
  }

  let { placeholder = "Select font…", previewFont = true, children, ...rest }: Props = $props();
  // Aliased to avoid colliding with the `$state` rune.
  const { store, state: fontState, ids, refs } = getContext<FontInputContext>(FONT_INPUT_KEY);
</script>

<button
  bind:this={refs.trigger}
  type="button"
  id={ids.trigger}
  aria-haspopup="listbox"
  aria-expanded={$fontState.open}
  aria-controls={$fontState.open ? ids.listbox : undefined}
  data-state={$fontState.open ? "open" : "closed"}
  data-placeholder={$fontState.value ? undefined : ""}
  style={previewFont && $fontState.value ? `font-family:"${$fontState.value}"` : undefined}
  onclick={() => store.toggle()}
  onkeydown={(e) => {
    if (handleComboboxKey(comboboxTarget(store), e)) e.preventDefault();
  }}
  {...rest}
>
  {#if children}{@render children($fontState.value)}{:else}{$fontState.value || placeholder}{/if}
</button>
